### ISSUE TITLE
How to keep track of target IDs

### ISSUE THREAD

**Issue by nwesem** [djape24394/gmphd_filter#1]
Hi @djape24394 
I have been testing your repository for online multi sensor multi target tracking and it's working pretty well, one thing I noticed is that you don't keep track of a target ID. Is that right? I may be missing something. I would like to have a consistent target ID such that I can track the previous positions of a certain target. Do you think that is possible? 
I would greatly appreciate your help on this.
Cheers nwesem

**Comment by djape24394** [comment]
Hy Niclas,

Well, this is the simplest implementation of the PHD filter, called
the Gaussian Mixture PHD filter, and the filter uses Random Finite Set
approach, where given the set(unordered collection) of estimated targets
states in the previous time step and measurement set for the current time step,
provides SET of estimated targets. So, it just returns the collection of
targets states without association with the ones from the previous sampling
moment. I know there are tweaks in the literature to get the actual
trajectories of the targets, but I haven't played with anything regarding
that case, so I can not tell you what would be some simple and reliable method.

These are the publications from the guy who invented the GMPHD filter:
http://ba-ngu.vo-au.com/publications.html
Maybe you can find this useful. Try to google papers regarding GMPHD and
"trajectory estimation", or "track continuity".

I know that this response doesn't solve your problem, but I hope it can
help you a little bit. 

Kind regards,
Predrag Vasilic

**Comment by nwesem** [comment]
Thanks a lot for your response. I will look further into this
